import rawFields from './data/fields.json';
import type {
  CourseMap, Course, FieldsFile, Gap, Ghost, Group, Lecture, Level, PathwayFile, Rect, Edge,
  SubjectFile, Version, ViewsFile,
} from './types';

/** Parent group every pathway hangs off; gives them their own page and URL prefix. */
export const PATHWAYS_GROUP = 'pathways';

/**
 * The map is split across data files: fields.json is the atlas (all field and
 * subject groups, cross-subject edges, ghosts); each data/subjects/<id>.json
 * holds one subject's courses and internal edges; each data/pathways/<id>.json
 * is one sequence through courses that already exist. Merged here at build time.
 */
function loadMap(): CourseMap {
  const fields = rawFields as FieldsFile;
  const merged: CourseMap = {
    groups: fields.groups,
    courses: {},
    edges: [...fields.edges],
    ghosts: [...fields.ghosts],
    gaps: {},
    pathwayEdges: {},
  };
  const subjectFiles = import.meta.glob('./data/subjects/*.json', {
    eager: true,
    import: 'default',
  }) as Record<string, SubjectFile>;
  for (const [path, file] of Object.entries(subjectFiles)) {
    const subjectId = path.replace(/^.*\//, '').replace(/\.json$/, '');
    if (!merged.groups[subjectId]) {
      console.warn(`subjects/${subjectId}.json has no matching group in fields.json`);
    }
    for (const [courseId, course] of Object.entries(file.courses)) {
      if (merged.courses[courseId]) {
        console.warn(`duplicate course id "${courseId}" in subjects/${subjectId}.json`);
      }
      merged.courses[courseId] = { ...course, group: subjectId };
    }
    if (file.edges) merged.edges.push(...file.edges);
  }

  const pathwayFiles = import.meta.glob('./data/pathways/*.json', {
    eager: true,
    import: 'default',
  }) as Record<string, PathwayFile>;
  for (const [path, file] of Object.entries(pathwayFiles)) {
    const id = path.replace(/^.*\//, '').replace(/\.json$/, '');
    merged.groups[id] = {
      title: file.title,
      parent: PATHWAYS_GROUP,
      kind: file.kind,
      blurb: file.blurb,
      source: file.source,
      field: file.field,
    };
    for (const step of file.steps) {
      if (!merged.courses[step.course]) {
        console.warn(`pathways/${id}.json references unknown course "${step.course}"`);
        continue;
      }
      merged.ghosts.push({ node: step.course, inGroup: id, pos: step.pos, note: step.note });
    }
    for (const gap of file.gaps ?? []) {
      merged.gaps[gap.id] = { ...gap, inGroup: id };
    }
    merged.pathwayEdges[id] = file.edges ?? [];
  }
  return merged;
}

export const map = loadMap();

/** Per-lecture view snapshots keyed by playlist id — generated by scripts/fetch-views.py */
const viewsFiles = import.meta.glob('./data/views/*.json', {
  eager: true,
  import: 'default',
}) as Record<string, ViewsFile>;

export function playlistId(version: Version): string | undefined {
  return version.youtube?.match(/[?&]list=([A-Za-z0-9_-]+)/)?.[1];
}

/** Lecture-by-lecture view counts for a version's playlist, if snapshotted. */
export function lecturesFor(version: Version): Lecture[] | undefined {
  const pid = playlistId(version);
  if (!pid) return undefined;
  return viewsFiles[`./data/views/${pid}.json`]?.lectures;
}

/** University logos in public/logos/ — schools not listed fall back to plain text. */
const LOGOS: Record<string, string> = {
  MIT: '/logos/mit.svg',
  Harvard: '/logos/harvard.svg',
  Stanford: '/logos/stanford.svg',
  Yale: '/logos/yale.svg',
  'UC Santa Cruz': '/logos/uc-santa-cruz.svg',
  'UC Berkeley': '/logos/uc-berkeley.svg',
};

export function logoFor(university?: string): string | undefined {
  return university ? LOGOS[university] : undefined;
}

/** Book covers live in public/covers/ as <slug>.png — drop a file in and it appears. */
export function coverUrl(slug?: string): string | undefined {
  return slug ? `/covers/${slug}.png` : undefined;
}

export function formatViews(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1).replace(/\.0$/, '')}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K`;
  return String(n);
}

// Node dimensions (course nodes are fixed-size; groups carry their own size)
export const COURSE_W = 220;
export const COURSE_H = 168;
export const COURSE_H_COMPACT = 60;
export const GHOST_W = 200;
export const GHOST_H = 56;

/** Compact mode: course cards collapse to title-only boxes — synced from App state. */
let compactCourses = false;

export function setCompactCourses(v: boolean) {
  compactCourses = v;
}

export function isCompact(): boolean {
  return compactCourses;
}

export function courseRect(c: Course): Rect {
  return { x: c.pos.x, y: c.pos.y, w: COURSE_W, h: compactCourses ? COURSE_H_COMPACT : COURSE_H };
}

/** Pathway steps carry commentary, so they get a wider card than a bare reference. */
export const GHOST_W_NOTED = 270;

export function ghostWidth(g: Ghost): number {
  return g.note ? GHOST_W_NOTED : GHOST_W;
}

/** Ghost label wrapped to fit the box width — long course titles take two lines. */
export function ghostTitleLines(g: Ghost): string[] {
  const target = map.courses[g.node] ?? map.groups[g.node];
  return wrapText('↪ ' + (target?.title ?? g.node), g.note ? 30 : 22);
}

/** A step's note, wrapped — pathway steps carry one, plain ghosts don't. */
export function ghostNoteLines(g: Ghost): string[] {
  return g.note ? wrapText(g.note, 38, 4) : [];
}

export function ghostRect(g: Ghost): Rect {
  const noteLines = ghostNoteLines(g);
  const h =
    GHOST_H +
    (ghostTitleLines(g).length - 1) * 18 +
    (noteLines.length > 0 ? noteLines.length * 15 + 6 : 0);
  return { x: g.pos.x, y: g.pos.y, w: ghostWidth(g), h };
}

// Gap nodes are wider than ghosts: they carry a reason and a list of alternates
export const GAP_W = 300;

/**
 * Label for one alternate. School first: it is the part that makes the offer
 * meaningful, and it is the part a truncated title would otherwise eat.
 */
export function gapAltLabel(courseId: string): string {
  const c = map.courses[courseId];
  const label = c.university ? `${c.university} · ${c.title}` : c.title;
  return wrapText('↪ ' + label, 42, 1)[0];
}

export function gapTitleLines(g: Gap): string[] {
  return wrapText(g.title, 26);
}

export function gapNoteLines(g: Gap): string[] {
  return g.note ? wrapText(g.note, 32, 3) : [];
}

/** Alternates that actually resolve to a course the school filter still shows. */
export function gapAlternates(g: Gap): string[] {
  return (g.alternates ?? []).filter((id) => map.courses[id] && courseVisible(map.courses[id]));
}

/**
 * Stacked layout offsets inside a gap node, shared by the geometry and the
 * renderer so edges land on the box the user actually sees.
 */
export const GAP_TITLE_TOP = 26;
export const GAP_TITLE_LINE = 19;
export const GAP_STATUS_GAP = 22;
export const GAP_NOTE_TOP = 17;
export const GAP_NOTE_LINE = 14;
export const GAP_ALTS_TOP = 22;
export const GAP_ALT_ROW = 20;

export function gapRect(g: Gap): Rect {
  const titles = gapTitleLines(g).length;
  const notes = gapNoteLines(g).length;
  const alts = gapAlternates(g).length;
  const h =
    GAP_TITLE_TOP +
    (titles - 1) * GAP_TITLE_LINE +
    GAP_STATUS_GAP +
    (notes > 0 ? GAP_NOTE_TOP + (notes - 1) * GAP_NOTE_LINE : 0) +
    (alts > 0 ? GAP_ALTS_TOP + alts * GAP_ALT_ROW : 0) +
    14;
  return { x: g.pos.x, y: g.pos.y, w: GAP_W, h };
}

export function gapsIn(groupId: string): Gap[] {
  return Object.values(map.gaps).filter((g) => g.inGroup === groupId);
}

/** Hide prerequisite arrows and ghost cards on the map — synced from App state. */
let hidePrereqs = false;

export function setHidePrereqs(v: boolean) {
  hidePrereqs = v;
}

/** Schools hidden by the settings filter — synced from App state before each render. */
let hiddenSchools: ReadonlySet<string> = new Set();

export function setHiddenSchools(schools: ReadonlySet<string>) {
  hiddenSchools = schools;
}

/** Every university that appears in the data, alphabetical. */
export function allSchools(): string[] {
  const schools = new Set<string>();
  for (const c of Object.values(map.courses)) if (c.university) schools.add(c.university);
  return [...schools].sort();
}

/**
 * Universities the landing page name-drops, most courses first. Filtered schools
 * are left out — naming a school whose courses the map is currently hiding would
 * promise something the visitor can't see.
 */
export function schoolsByCourseCount(): string[] {
  const counts = new Map<string, number>();
  for (const c of Object.values(map.courses)) {
    if (c.university && courseVisible(c)) {
      counts.set(c.university, (counts.get(c.university) ?? 0) + 1);
    }
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([school]) => school);
}

/** Levels hidden by the settings filter — synced from App state before each render. */
let hiddenLevels: ReadonlySet<string> = new Set();

export function setHiddenLevels(levels: ReadonlySet<string>) {
  hiddenLevels = levels;
}

/** Display names for the level filter and badges, in course order. */
export const LEVELS: { id: Level; label: string }[] = [
  { id: 'undergrad', label: 'Undergrad' },
  { id: 'grad', label: 'Grad' },
];

export function levelLabel(level: Level): string {
  return LEVELS.find((l) => l.id === level)?.label ?? level;
}

/** Courses with no school or no level are never hidden — you can't filter on absent data. */
function courseVisible(c: Course): boolean {
  return (
    (!c.university || !hiddenSchools.has(c.university)) &&
    (!c.level || !hiddenLevels.has(c.level))
  );
}

/** Recursive course count ignoring the school filter. */
export function totalCourseCount(groupId: string): number {
  return (
    Object.values(map.courses).filter((c) => c.group === groupId).length +
    Object.keys(map.groups)
      .filter((id) => map.groups[id].parent === groupId)
      .reduce((sum, id) => sum + totalCourseCount(id), 0)
  );
}

/**
 * A group vanishes only when the filter is what emptied it — groups that never
 * had courses (empty scaffolding) stay visible regardless of the filter.
 */
function groupFilteredOut(groupId: string): boolean {
  return (
    (hiddenSchools.size > 0 || hiddenLevels.size > 0) &&
    courseCount(groupId) === 0 &&
    totalCourseCount(groupId) > 0
  );
}

/** Chain of group ids from root down to the given group. */
export function groupChain(groupId: string): string[] {
  const chain: string[] = [];
  let cur: string | undefined = groupId;
  while (cur && map.groups[cur] && !chain.includes(cur)) {
    chain.unshift(cur);
    cur = map.groups[cur].parent;
  }
  return chain;
}

export function childGroups(groupId: string): string[] {
  return Object.keys(map.groups).filter(
    (id) => map.groups[id].parent === groupId && !groupFilteredOut(id)
  );
}

export function coursesIn(groupId: string): string[] {
  return Object.keys(map.courses).filter(
    (id) => map.courses[id].group === groupId && courseVisible(map.courses[id])
  );
}

/** True for a pathway's own page — pathway groups are the ones carrying a kind. */
export function isPathway(groupId: string): boolean {
  return map.groups[groupId]?.kind !== undefined;
}

/** Every pathway, in data order, for the landing page. */
export function pathways(): Array<{ id: string; group: Group }> {
  return Object.keys(map.groups)
    .filter((id) => map.groups[id].parent === PATHWAYS_GROUP)
    .map((id) => ({ id, group: map.groups[id] }));
}

/** Steps on a pathway, counting gaps — what the landing card advertises. */
export function pathwayStepCount(groupId: string): number {
  return map.ghosts.filter((g) => g.inGroup === groupId).length + gapsIn(groupId).length;
}

/** Schools appearing on a pathway, in step order, deduped. */
export function pathwaySchools(groupId: string): string[] {
  const out: string[] = [];
  for (const g of map.ghosts) {
    if (g.inGroup !== groupId) continue;
    const uni = map.courses[g.node]?.university;
    if (uni && !out.includes(uni)) out.push(uni);
  }
  return out;
}

export function ghostsIn(groupId: string): Ghost[] {
  // On a pathway the ghosts *are* the content, so "hide prerequisites" must not empty the page
  if (hidePrereqs && !isPathway(groupId)) return [];
  return map.ghosts.filter((g) => {
    if (g.inGroup !== groupId) return false;
    const course = map.courses[g.node];
    if (course) return courseVisible(course);
    return map.groups[g.node] !== undefined && !groupFilteredOut(g.node);
  });
}

/** Recursive count of courses inside a group (for the badge on group boxes). */
export function courseCount(groupId: string): number {
  return (
    coursesIn(groupId).length +
    childGroups(groupId).reduce((sum, id) => sum + courseCount(id), 0)
  );
}

export function prereqsOf(courseId: string): string[] {
  return map.edges.filter((e) => e.to === courseId).map((e) => e.from);
}

export function unlocksOf(courseId: string): string[] {
  return map.edges.filter((e) => e.from === courseId).map((e) => e.to);
}

/**
 * Edges drawable on a group's page: both endpoints must resolve to a rect —
 * a course node in this group, a child group's box, or a hand-placed ghost.
 */
export function edgesOn(groupId: string): Array<Edge & { fromRect: Rect; toRect: Rect }> {
  // A pathway's arrows are the sequence itself, not decoration the filter may drop
  if (hidePrereqs && !isPathway(groupId)) return [];
  const rects = new Map<string, Rect>();
  for (const id of coursesIn(groupId)) rects.set(id, courseRect(map.courses[id]));
  for (const id of childGroups(groupId)) {
    const g = map.groups[id];
    if (g.pos && g.size) rects.set(id, { x: g.pos.x, y: g.pos.y, w: g.size.w, h: g.size.h });
  }
  for (const g of gapsIn(groupId)) rects.set(g.id, gapRect(g));
  for (const g of ghostsIn(groupId)) if (!rects.has(g.node)) rects.set(g.node, ghostRect(g));
  const out: Array<Edge & { fromRect: Rect; toRect: Rect }> = [];
  // A pathway shows exactly the sequence it declares — no prerequisite edges
  // leaking in from the wider map to contradict its ordering
  const source = isPathway(groupId) ? map.pathwayEdges[groupId] ?? [] : map.edges;
  for (const e of source) {
    const fromRect = rects.get(e.from);
    const toRect = rects.get(e.to);
    if (fromRect && toRect) out.push({ ...e, fromRect, toRect });
  }
  return out;
}

/** Point where the segment from a rect's center toward `toward` exits the rect. */
export function borderPoint(r: Rect, toward: { x: number; y: number }): { x: number; y: number } {
  const cx = r.x + r.w / 2;
  const cy = r.y + r.h / 2;
  const dx = toward.x - cx;
  const dy = toward.y - cy;
  if (dx === 0 && dy === 0) return { x: cx, y: cy };
  const scaleX = dx !== 0 ? r.w / 2 / Math.abs(dx) : Infinity;
  const scaleY = dy !== 0 ? r.h / 2 / Math.abs(dy) : Infinity;
  const t = Math.min(scaleX, scaleY);
  return { x: cx + dx * t, y: cy + dy * t };
}

export function center(r: Rect): { x: number; y: number } {
  return { x: r.x + r.w / 2, y: r.y + r.h / 2 };
}

/** Stable positive integer seed per id so rough.js shapes don't jitter between renders. */
export function seedFor(id: string): number {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) | 0;
  return (Math.abs(h) % 2147483646) + 1;
}

export function primaryVersion(c: Course) {
  return c.versions.find((v) => v.primary) ?? c.versions[0];
}

/** When the course was offered: explicit term, else the primary version's date. */
export function courseTerm(c: Course): string | undefined {
  return c.term ?? primaryVersion(c)?.date;
}

export function thumbUrl(v: { youtubeId?: string; thumbnail?: string } | undefined): string | undefined {
  if (!v) return undefined;
  if (v.thumbnail) return v.thumbnail;
  if (v.youtubeId) return `https://i.ytimg.com/vi/${v.youtubeId}/mqdefault.jpg`;
  return undefined;
}

export function wrapText(text: string, maxChars: number, maxLines = 2): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let line = '';
  for (const w of words) {
    if (line && (line + ' ' + w).length > maxChars) {
      lines.push(line);
      line = w;
    } else {
      line = line ? line + ' ' + w : w;
    }
  }
  if (line) lines.push(line);
  if (lines.length > maxLines) {
    const kept = lines.slice(0, maxLines);
    kept[maxLines - 1] = kept[maxLines - 1].slice(0, maxChars - 1) + '…';
    return kept;
  }
  return lines;
}

export interface Route {
  /** The landing page — `#/` with nothing after it */
  landing?: boolean;
  groupId: string;
  courseId?: string;
}

export function parseHash(): Route {
  const hash = window.location.hash.replace(/^#\/?/, '');
  const [path, query] = hash.split('?');
  const segments = path.split('/').filter(Boolean);
  // Back-compat with old ?c= panel links
  const params = new URLSearchParams(query ?? '');
  const c = params.get('c') ?? undefined;
  const panelCourse = c && map.courses[c] ? c : undefined;
  if (segments.length === 0 && !panelCourse) return { landing: true, groupId: 'root' };
  const last = segments[segments.length - 1];
  if (last && map.courses[last]) {
    // The segment before a course names the page it was opened from, so a course
    // reached through a pathway keeps that context instead of jumping home
    const parent = segments[segments.length - 2];
    const groupId = parent && map.groups[parent] ? parent : map.courses[last].group;
    return { groupId, courseId: last };
  }
  const groupId = last && map.groups[last] ? last : 'root';
  return { groupId, courseId: panelCourse };
}

/** `#/` is the landing, so the root map needs a segment of its own. */
const MAP_SEGMENT = 'map';

export function routeHash(groupId: string, courseId?: string): string {
  const path = groupChain(groupId).filter((id) => id !== 'root');
  if (courseId && map.courses[courseId]) path.push(courseId);
  return path.length > 0 ? '#/' + path.join('/') : '#/' + MAP_SEGMENT;
}

export function landingHash(): string {
  return '#/';
}
