import rawFields from './data/fields.json';
import type {
  CourseMap, Course, FieldsFile, Ghost, Lecture, Rect, Edge, SubjectFile, Version, ViewsFile,
} from './types';

/**
 * The map is split across data files: fields.json is the atlas (all field and
 * subject groups, cross-subject edges, ghosts); each data/subjects/<id>.json
 * holds one subject's courses and internal edges. Merged here at build time.
 */
function loadMap(): CourseMap {
  const fields = rawFields as FieldsFile;
  const merged: CourseMap = {
    groups: fields.groups,
    courses: {},
    edges: [...fields.edges],
    ghosts: fields.ghosts,
  };
  const subjectFiles = import.meta.glob('./data/subjects/*.json', {
    eager: true,
    import: 'default',
  }) as Record<string, SubjectFile>;
  for (const [path, file] of Object.entries(subjectFiles)) {
    const subjectId = path.replace(/^.*\//, '').replace(/\.json$/, '');
    if (!merged.groups[subjectId]) {
      console.warn(`subjects/${subjectId}.json has no matching group in fields.json`);
    }
    for (const [courseId, course] of Object.entries(file.courses)) {
      if (merged.courses[courseId]) {
        console.warn(`duplicate course id "${courseId}" in subjects/${subjectId}.json`);
      }
      merged.courses[courseId] = { ...course, group: subjectId };
    }
    if (file.edges) merged.edges.push(...file.edges);
  }
  return merged;
}

export const map = loadMap();

/** Per-lecture view snapshots keyed by playlist id — generated by scripts/fetch-views.py */
const viewsFiles = import.meta.glob('./data/views/*.json', {
  eager: true,
  import: 'default',
}) as Record<string, ViewsFile>;

export function playlistId(version: Version): string | undefined {
  return version.youtube?.match(/[?&]list=([A-Za-z0-9_-]+)/)?.[1];
}

/** Lecture-by-lecture view counts for a version's playlist, if snapshotted. */
export function lecturesFor(version: Version): Lecture[] | undefined {
  const pid = playlistId(version);
  if (!pid) return undefined;
  return viewsFiles[`./data/views/${pid}.json`]?.lectures;
}

/** University logos in public/logos/ — schools not listed fall back to plain text. */
const LOGOS: Record<string, string> = {
  MIT: '/logos/mit.svg',
  Harvard: '/logos/harvard.svg',
  Stanford: '/logos/stanford.svg',
  Yale: '/logos/yale.svg',
};

export function logoFor(university?: string): string | undefined {
  return university ? LOGOS[university] : undefined;
}

export function formatViews(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1).replace(/\.0$/, '')}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K`;
  return String(n);
}

// Node dimensions (course nodes are fixed-size; groups carry their own size)
export const COURSE_W = 220;
export const COURSE_H = 168;
export const GHOST_W = 200;
export const GHOST_H = 56;

export function courseRect(c: Course): Rect {
  return { x: c.pos.x, y: c.pos.y, w: COURSE_W, h: COURSE_H };
}

export function ghostRect(g: Ghost): Rect {
  return { x: g.pos.x, y: g.pos.y, w: GHOST_W, h: GHOST_H };
}

/** Chain of group ids from root down to the given group. */
export function groupChain(groupId: string): string[] {
  const chain: string[] = [];
  let cur: string | undefined = groupId;
  while (cur && map.groups[cur] && !chain.includes(cur)) {
    chain.unshift(cur);
    cur = map.groups[cur].parent;
  }
  return chain;
}

export function childGroups(groupId: string): string[] {
  return Object.keys(map.groups).filter((id) => map.groups[id].parent === groupId);
}

export function coursesIn(groupId: string): string[] {
  return Object.keys(map.courses).filter((id) => map.courses[id].group === groupId);
}

export function ghostsIn(groupId: string): Ghost[] {
  return map.ghosts.filter(
    (g) => g.inGroup === groupId && (map.courses[g.node] || map.groups[g.node])
  );
}

/** Recursive count of courses inside a group (for the badge on group boxes). */
export function courseCount(groupId: string): number {
  return (
    coursesIn(groupId).length +
    childGroups(groupId).reduce((sum, id) => sum + courseCount(id), 0)
  );
}

export function prereqsOf(courseId: string): string[] {
  return map.edges.filter((e) => e.to === courseId).map((e) => e.from);
}

export function unlocksOf(courseId: string): string[] {
  return map.edges.filter((e) => e.from === courseId).map((e) => e.to);
}

/**
 * Edges drawable on a group's page: both endpoints must resolve to a rect —
 * a course node in this group, a child group's box, or a hand-placed ghost.
 */
export function edgesOn(groupId: string): Array<Edge & { fromRect: Rect; toRect: Rect }> {
  const rects = new Map<string, Rect>();
  for (const id of coursesIn(groupId)) rects.set(id, courseRect(map.courses[id]));
  for (const id of childGroups(groupId)) {
    const g = map.groups[id];
    if (g.pos && g.size) rects.set(id, { x: g.pos.x, y: g.pos.y, w: g.size.w, h: g.size.h });
  }
  for (const g of ghostsIn(groupId)) if (!rects.has(g.node)) rects.set(g.node, ghostRect(g));
  const out: Array<Edge & { fromRect: Rect; toRect: Rect }> = [];
  for (const e of map.edges) {
    const fromRect = rects.get(e.from);
    const toRect = rects.get(e.to);
    if (fromRect && toRect) out.push({ ...e, fromRect, toRect });
  }
  return out;
}

/** Point where the segment from a rect's center toward `toward` exits the rect. */
export function borderPoint(r: Rect, toward: { x: number; y: number }): { x: number; y: number } {
  const cx = r.x + r.w / 2;
  const cy = r.y + r.h / 2;
  const dx = toward.x - cx;
  const dy = toward.y - cy;
  if (dx === 0 && dy === 0) return { x: cx, y: cy };
  const scaleX = dx !== 0 ? r.w / 2 / Math.abs(dx) : Infinity;
  const scaleY = dy !== 0 ? r.h / 2 / Math.abs(dy) : Infinity;
  const t = Math.min(scaleX, scaleY);
  return { x: cx + dx * t, y: cy + dy * t };
}

export function center(r: Rect): { x: number; y: number } {
  return { x: r.x + r.w / 2, y: r.y + r.h / 2 };
}

/** Stable positive integer seed per id so rough.js shapes don't jitter between renders. */
export function seedFor(id: string): number {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) | 0;
  return (Math.abs(h) % 2147483646) + 1;
}

export function primaryVersion(c: Course) {
  return c.versions.find((v) => v.primary) ?? c.versions[0];
}

/** When the course was offered: explicit term, else the primary version's date. */
export function courseTerm(c: Course): string | undefined {
  return c.term ?? primaryVersion(c)?.date;
}

export function thumbUrl(v: { youtubeId?: string; thumbnail?: string } | undefined): string | undefined {
  if (!v) return undefined;
  if (v.thumbnail) return v.thumbnail;
  if (v.youtubeId) return `https://i.ytimg.com/vi/${v.youtubeId}/mqdefault.jpg`;
  return undefined;
}

export function wrapText(text: string, maxChars: number, maxLines = 2): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let line = '';
  for (const w of words) {
    if (line && (line + ' ' + w).length > maxChars) {
      lines.push(line);
      line = w;
    } else {
      line = line ? line + ' ' + w : w;
    }
  }
  if (line) lines.push(line);
  if (lines.length > maxLines) {
    const kept = lines.slice(0, maxLines);
    kept[maxLines - 1] = kept[maxLines - 1].slice(0, maxChars - 1) + '…';
    return kept;
  }
  return lines;
}

export interface Route {
  groupId: string;
  courseId?: string;
}

export function parseHash(): Route {
  const hash = window.location.hash.replace(/^#\/?/, '');
  const [path, query] = hash.split('?');
  const segments = path.split('/').filter(Boolean);
  const last = segments[segments.length - 1];
  // Subject page: the last path segment is a course id
  if (last && map.courses[last]) {
    return { groupId: map.courses[last].group, courseId: last };
  }
  const groupId = last && map.groups[last] ? last : 'root';
  // Back-compat with old ?c= panel links
  const params = new URLSearchParams(query ?? '');
  const c = params.get('c') ?? undefined;
  return { groupId, courseId: c && map.courses[c] ? c : undefined };
}

export function routeHash(groupId: string, courseId?: string): string {
  if (courseId && map.courses[courseId]) {
    const path = groupChain(map.courses[courseId].group).filter((id) => id !== 'root');
    return '#/' + [...path, courseId].join('/');
  }
  const path = groupChain(groupId).filter((id) => id !== 'root');
  return '#/' + path.join('/');
}
