export interface XY {
  x: number;
  y: number;
}

export interface Version {
  label: string;
  /** Course homepage (OCW, university site, …) */
  url?: string;
  /** YouTube playlist for the lectures */
  youtube?: string;
  /** When this run of the course took place, e.g. "Fall 2020" */
  date?: string;
  /** YouTube video id — used to derive a thumbnail, no scraping involved */
  youtubeId?: string;
  /** Explicit thumbnail URL for non-YouTube sources */
  thumbnail?: string;
  primary?: boolean;
}

export interface Course {
  title: string;
  university?: string;
  /** When the course was offered, e.g. "Fall 2020" — defaults to the primary version's date */
  term?: string;
  /** Subject this course belongs to — stamped from the subject filename at load */
  group: string;
  pos: XY;
  versions: Version[];
}

/** A field (Math, Physics, …) or a subject (Quantum Mechanics, …) — same recursive shape */
export interface Group {
  title: string;
  parent?: string;
  /** Position and size of this group's box on its parent's page */
  pos?: XY;
  size?: { w: number; h: number };
}

export interface Edge {
  /** course or group id that should be done first */
  from: string;
  /** course or group id that depends on it */
  to: string;
}

export interface Ghost {
  /** course or group id this ghost references */
  node: string;
  /** group page the ghost is placed on */
  inGroup: string;
  pos: XY;
}

export interface CourseMap {
  groups: Record<string, Group>;
  courses: Record<string, Course>;
  edges: Edge[];
  ghosts: Ghost[];
}

/** Shape of data/fields.json: the atlas — all groups, plus everything that spans subjects */
export interface FieldsFile {
  groups: Record<string, Group>;
  edges: Edge[];
  ghosts: Ghost[];
}

/** Shape of data/subjects/<subject-id>.json; the filename is the subject id */
export interface SubjectFile {
  courses: Record<string, Omit<Course, 'group'>>;
  /** Edges between this subject's own courses */
  edges?: Edge[];
}

export interface Lecture {
  title: string;
  views: number;
}

/** Shape of data/views/<playlistId>.json — generated by scripts/fetch-views.py */
export interface ViewsFile {
  lectures: Lecture[];
}

export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}
